services:
  back-nest:
    build:
      context: ../packages/back-nest
      dockerfile: Dockerfile
    env_file:
      - ../packages/back-nest/.env.production
    ports:
      - "${BACK_NEST_APP_PORT}:${BACK_NEST_CONTAINER_PORT}"
    environment:
      - NODE_ENV=production
    command: npm run start:prod  # Run the production server

  front-react:
    build:
      context: ../packages/front-react
      dockerfile: Dockerfile
    env_file:
      - ../packages/front-react/.env.production
    ports:
      - "${FRONT_REACT_APP_PORT}:${FRONT_REACT_CONTAINER_PORT}"
    environment:
      - NODE_ENV=production
    command: serve -s build  # Serve static files after building

